export default function Head() {
  return (
    <>
      <title>Auxiliar Manipuladora del Cartón</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logoIco-01.ico" />
    </>
  )
}
